### ISSUE TITLE
RFC: Allow usage of remote connections?

### ISSUE THREAD

**Issue by joelgriffith** [jdobosz/testcafe-browser-provider-puppeteer#10]
Hey folks! I’m the maintainer if Browserless (a docker/hosted service for puppeteer). I’d love to contribute to this repo instead of building it myself, and to that end I’m looking to add a remote connections as part of this plugin.

My first idea is to allow a remote URL in your provider string, similar to how you allow the path of the binary executable. Would just be a condition to check if that part of the string is a path or fully-qualified URL. Can do a quick PR if that helps!

**Comment by jdobosz** [comment]
PR is warmly welcomed, however I’m not quite sure, I understand the purpose of this extension.
Could you please outline the use case?

**Comment by joelgriffith** [comment]
Thanks @jdobosz. I've done a bit of R&D and determined that testcafé isn't a good model for browserless since it depends on a local webserver for running tests (and browserless doesn't have native tunneling capabilities).

I'll continue to look into this on my own and see if I can revisit this later.
