### ISSUE TITLE
Browser process is not closed in the closeBrowser method

### ISSUE THREAD

**Issue by AndreyBelym** [jdobosz/testcafe-browser-provider-puppeteer#3]
In the `closeBrowser` method only the opened page gets closed. The browser process remains open and can prevent process termination in case of tests started through TestCafe API (e.g. `gulp-testcafe`). Puppeteer's `browser.close()` method should be called in the `closeBrowser` method to prevent this behavior.

**Comment by jdobosz** [comment]
Thx for pointing that. I fixed it in the  new release 1.3.1.
Please feel free to open PR next time.

**Comment by AndreyBelym** [comment]
Ok, thanks for fixing it!
