### ISSUE TITLE
Puppeteer 1.5.0 Doesn't work 

### ISSUE THREAD

**Issue by robokozo** [jdobosz/testcafe-browser-provider-puppeteer#4]
Version 1.3.2 of this has a dependency on 1.4.0 of Puppeteer. It worked just fine when I installed it a little over a week ago using 1.4 of Puppeteer. However new installs seem to be pulling 1.5.0 puppeteer which doesn't seem to work.

When running my tests I get:
14:36:56 ERROR: The process "9700" not found.
14:36:56 ERROR Was unable to open the browser "puppeteer:" due to error.
14:36:56 
14:36:56 Error: Failed to launch chrome!
14:36:56 [0613/143656.027:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from \node_modules\puppeteer\.local-chromium\win64-564778\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)

**Comment by jdobosz** [comment]
Ok, I published 1.3.3 where puppeteer 1.4.0 is pinned.

Kind regards

Jacek

**Comment by robokozo** [comment]
I tried installing 1.3.2 again which tries to download puppeteer 1.7 and it works again. Maybe you can add the ^ to the version again

**Comment by ptashek** [comment]
This was resolved in 1.4.0, which works with puppeteer 1.4.0 all the way up-to 1.12.2 (as of today).
