### ISSUE TITLE
Using preexisting chromium 

### ISSUE THREAD

**Issue by AndrewKohnen** [jdobosz/testcafe-browser-provider-puppeteer#7]
node version 8.10
testcafe version 0.20

##Here is my issue

I have been using this package to run testcafe on a Jenkins server. It was working nicely but the Jenkins has been restructured. Now agents are generate via docker and these agents can't download chromium but do come with puppeteer and chromium pre-installed. 

What I'd like to do is use this package but provide it an existing puppeteer or chromium as opposed to it downloading a new puppeteer every time we wish ti use it.

**Comment by jdobosz** [comment]
Implemented in Version 1.4.0
